### ISSUE TITLE
genereate mock data api file with undefined when new api added

### ISSUE THREAD

**Issue by derek-sz** [lincolnlau/swagger-jsblade#12]
when the swagger file add new API, and run `blade mock ./swagger/crm.pc.swagger.json -f ./mock/mock.json`. it generate new mock files which only contains undefined

**Comment by whq731** [comment]
可以稳定复现吗？

**Comment by derek-sz** [comment]
是的, 稳定复现. 新生成的文件都是undefined

**Comment by whq731** [comment]
@MechanicianW
